[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = adafruit/MAX6675 library@^1.1.2, bblanchon/ArduinoJson@^7.0.0
build_flags = -D CORE_DEBUG_LEVEL=3
