[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = adafruit/MAX6675 library@^1.1.2, bblanchon/ArduinoJson@^7.0.0, ESP32Async/ESPAsyncWebServer, ESP32Async/AsyncTCP, knolleary/PubSubClient@^2.8
build_flags = -D CORE_DEBUG_LEVEL=3
board_build.filesystem = littlefs
